import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import Header from "./components/header";
import Sidenav from "./components/side-nav";
import PageWrapper from "./components/page-wrapper";
import MarginWidthWrapper from "./components/margin-width-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

if (!process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY) {
  throw 'Missing Publishable Key'
}

const clerkPubKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey={clerkPubKey}>
      <html lang="en">
        <body className={`bg-white ${inter.className}`}>
          <SignedOut>
            {children}
          </SignedOut>

          <SignedIn>
            <div className="flex">
              <Sidenav />
              <main className="flex-1">
                <MarginWidthWrapper>
                  <Header />
                  <PageWrapper>
                    {children}
                  </PageWrapper>
                </MarginWidthWrapper>
              </main>
            </div>
          </SignedIn>
        </body>
      </html>
    </ClerkProvider>
  );
}
